---
# =============================================================================
# Helix Stax - Production Overrides
# =============================================================================

crowdsec_console_enroll: false
