services:
  zitadel:
    image: ghcr.io/zitadel/zitadel:stable
    container_name: zitadel
    restart: unless-stopped
    command: start-from-init --masterkeyFile /masterkey --tlsMode disabled
    ports:
      - "127.0.0.1:8082:8082"
    volumes:
      - /opt/helix-stax/zitadel/masterkey:/masterkey:ro
    environment:
      ZITADEL_PORT: "8082"
      ZITADEL_EXTERNALDOMAIN: auth.helixstax.net
      ZITADEL_EXTERNALSECURE: "true"
      ZITADEL_EXTERNALPORT: "443"
      ZITADEL_DATABASE_POSTGRES_HOST: helix-postgres
      ZITADEL_DATABASE_POSTGRES_PORT: "5432"
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: "iBpcYUbwxC4ff1GilVE69gICMdY4H5De"
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: "gtNDO91tN2Pv0HmEdLReQffkWOYIznYmnDjKVU8edtU="
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_FIRSTINSTANCE_ORG_NAME: "Helix Stax"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: wakeem
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: "6oZcTK6MEtTAKAN5z51png=="
    networks:
      - helix-net

networks:
  helix-net:
    external: true
