---
- name: Restart crowdsec
  ansible.builtin.systemd:
    name: crowdsec
    state: restarted
    enabled: true

- name: Restart crowdsec-firewall-bouncer
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
    enabled: true
